# Generated by Django 5.1.5 on 2025-01-29 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT'), ('bussiness', 'BUSSINESS')], max_length=50)),
                ('id_type', models.CharField(choices=[('adhar_card', 'ADHAR_CARD'), ('driver', 'DRIVER LICENECE'), ('passport', 'PASSPORT')], max_length=50)),
                ('employment_status', models.CharField(choices=[('employed', 'EMPLOYED'), ('unemployed', 'UNEMPLOYED'), ('retired', 'RETIRED'), ('student', 'STUDENT')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
