# Generated by Django 5.1.5 on 2025-01-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='id_num',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
