# Generated by Django 5.1.5 on 2025-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_customerprofile_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_number',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
