# Generated by Django 5.1.5 on 2025-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_deposit_deposittable_delete_deposittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
