# Generated by Django 5.1.5 on 2025-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_kseb_billpay_bill_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kseb_billpay',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
