# Generated by Django 5.1.5 on 2025-02-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_kseb_billpay_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kseb_billpay',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kseb_billpay',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
