# Generated by Django 5.1.5 on 2025-02-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_kseb_billpay_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=20, unique=True)),
                ('bill_number', models.CharField(max_length=30, unique=True)),
                ('bill_amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('billing_month', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount_paid', models.IntegerField()),
                ('mode_of_payment', models.CharField(choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
