# Generated by Django 5.1.5 on 2025-02-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_waterbillpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillpayment',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
