# Generated by Django 5.1.5 on 2025-02-18 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_deposittransaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kseb_billpay',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
    ]
