# Generated by Django 5.1.5 on 2025-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_alter_kseb_billpay_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kseb_billpay',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
