# Generated by Django 5.1.5 on 2025-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_kseb_billpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbillpayment',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
