# Generated by Django 5.1.5 on 2025-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_waterbillpayment_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillpayment',
            name='billing_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterbillpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
