# Generated by Django 5.1.5 on 2025-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0019_cardrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id_type',
            field=models.CharField(choices=[('adhar_card', 'ADHAR_CARD'), ('pan_card', 'PAN_CARD')], max_length=50),
        ),
    ]
