# Generated by Django 5.1.5 on 2025-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_alter_customerprofile_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
