# Generated by Django 5.1.2 on 2025-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_cardrequest_adhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
